apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-server
  - discovery-server
  - api-gateway
  - customers-service
  - visits-service
  - vets-service
  - genai-service
  - admin-server
